### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ishanray** [fuzetsu/web-novel-reader#1]
Nice project. What are you using it for?

Still using Mithril?

**Comment by fuzetsu** [comment]
Hey @ishanray, been a while! 😄 

I use it to read web novels and load multiple chapters on the screen at once. Originally it was to use iOS's screen reader feature while going on longer walks, so that I wouldn't have to keep pressing next chapter as often, and so that I could filter out all the random crap on the website that the screen reader feature would read. I kind of abuse aria-hidden in this project to hide everything except for the chapter content from screen readers.

Recently though I've been using [elevenreader](https://elevenlabs.io/text-reader) (which is completely free atm), to listen instead of the iOS TTS, but this tool still helps me quickly scrape a bunch of chapters and [copy it to clipboard with one action](https://github.com/fuzetsu/web-novel-reader/blob/main/src/cmp/App/App.tsx#L183-L201) to paste into the elevenreader. 

> Still using Mithril?

Not as much recently, but I still dip into in a couple older projects.

I have been messing around with SolidJS recently, enjoying experimenting with the deep reactivity mental model instead of the mithril/react style vdom one.

How about you, what are you into these days?

**Comment by ishanray** [comment]
Something in the ebook reading space. Interested to know what you think about it. Email me at ishan dot iipm at gmail
